language: ruby
before_install: gem install bundler -v 1.14.6
bundler_args: "--without development"
script:
  - "cat Gemfile.lock"
  - "bundle exec rake $CHECK"
cache: bundler

rvm:
  - 2.4.1
env:
 - "CHECK=c"
 - "CHECK=spec"
 - "CHECK=rubocop"

matrix:
  exclude:
    - rvm: 2.1.9
      env: "CHECK=rubocop"
  include:
    - rvm: 2.1.9
      env: "CHECK=acceptance:local"


